// Dropdown options copied from Kiron's HubSpot deal properties (configuration, not
// client data), so KRM fields match what the team uses today and the HubSpot import lines up.
// Admins can add or rename options afterwards in Admin → Fields.

// HubSpot "Country where operator is based" and "Market We Will Operate In".
export const COUNTRIES: string[] = [
  "Afghanistan",
  "Åland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Asia/Pacific Region",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "British Virgin Islands",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Caribbean Netherlands",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Europe",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern and Antarctic Lands",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia (FYROM)",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar (Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Islands",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Réunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Barthélemy",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "U.S. Virgin Islands",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Global",
  "TBA",
  "Africa",
  "LatAm"
];

// HubSpot "Product (Event Type)": the games list Kelly maintains.
export const PRODUCTS: string[] = [
  "3rd Party Content",
  "Archery",
  "Arm Wrestling",
  "Astro",
  "Aviator",
  "Badminton",
  "Basketball Group Products",
  "Bet On Numbers",
  "BIGS - Crab Roulette",
  "BIGS - Crab Roulette Christmas",
  "BIGS - Crab Roulette Halloween",
  "BIGS - Penguin Plunge",
  "BIGS - Penguin Plunge Christmas",
  "BIGS - Penguin Plunge Halloween",
  "BIGS - Roach Roulette",
  "BIGS - Roach Roulette Christmas",
  "BIGS - Roach Roulette Halloween",
  "Boxing",
  "Brazil Serie A league",
  "Brazil Serie A single game",
  "Cricket Final Over - Indian",
  "Cricket Final Over - World",
  "Cricket Group Products",
  "Cricket Super Over - Indian",
  "Cricket Super Over - World",
  "Cycle Racing",
  "Dashing Derby(Keno)",
  "Dashing Derby(Video Based)",
  "Dream Catcher",
  "English Keno Fast League",
  "English Keno Fast League Single Match",
  "Equal Odds Racing",
  "ESA - 12Deadly Spins",
  "ESA - Baccarat",
  "ESA - Basketball Mine",
  "ESA - Basketball Mine V2",
  "ESA - Big Fish Bonanza",
  "ESA - BlackJack",
  "ESA - BlackJack VIP",
  "ESA - Candy Drops",
  "ESA - Dragon Mine",
  "ESA - Egypt Mine",
  "ESA - Egypt Mine V2",
  "ESA - Egypt Reels",
  "ESA - EU Roulette",
  "ESA - EU Roulette'",
  "ESA - Fruit Bloxx",
  "ESA - Fruit Staxx",
  "ESA - Fruitz and Spinz",
  "ESA - Goal Mine",
  "ESA - Goal Mine World",
  "ESA - Joker Poker",
  "ESA - Pirate Mine",
  "ESA - Rocket Racers",
  "ESA - Rocket Racers PT",
  "ESA - Roulette PT Version",
  "ESA - Roulette VIP",
  "ESA - Santastic Ride",
  "ESA - Wild Vegas",
  "ESA - Zeus Gold",
  "Ezugi",
  "Fighter Jet",
  "Final Hoops",
  "Final Hoops League",
  "Final Hoops League Round",
  "Final Over Cricket",
  "Football Group Products",
  "Football League Week (Vsoft)",
  "FTV Nations League (Goal World Cup)",
  "Goal - Nations Football",
  "Goal - Nations League Round",
  "Goal - Nations Leagues Match",
  "Goal - World Cup Football",
  "Goal - World Cup Football Group",
  "Goal - World Cup Football Match",
  "Goal - World Cup Football Round",
  "Goal Football - American",
  "Goal Football - Brazilian",
  "Goal Football - Champions",
  "Goal Football - Chinese",
  "Goal Football - English",
  "Goal Football - Euro",
  "Goal Football - French",
  "Goal Football - German",
  "Goal Football - Greek",
  "Goal Football - Italian",
  "Goal Football - Morocco",
  "Goal Football - Spanish",
  "Goal Football - Turkish",
  "Goal Football League Match - American",
  "Goal Football League Match - Brazilian",
  "Goal Football League Match - English",
  "Goal Football League Match - Euro",
  "Goal Football League Match - Greek",
  "Goal Football League Match - Italian",
  "Goal Football League Match - Morocco",
  "Goal Football League Match - Spanish",
  "Goal Football League Round - American",
  "Goal Football League Round - Brazilian",
  "Goal Football League Round - Champions",
  "Goal Football League Round - Chinese",
  "Goal Football League Round - English",
  "Goal Football League Round - Euro",
  "Goal Football League Round - French",
  "Goal Football League Round - German",
  "Goal Football League Round - Greek",
  "Goal Football League Round - Italian",
  "Goal Football League Round - Morocco",
  "Goal Football League Round - Spanish",
  "Goal Football League Round - Turkish",
  "Golf",
  "Golf (Up and Down)",
  "Greyhound",
  "Harness Racing",
  "Horse Racing Roulette",
  "Horse Racing Roulette V2",
  "Horses",
  "Ice Hockey",
  "Ice Hockey - Stars (American)",
  "Ice Hockey League Match - Stars (American)",
  "Ice Hockey League Round",
  "Ice Hockey League Round - Stars (American)",
  "iGoal",
  "iGoal Football - Brazilian",
  "iGoal Football - English",
  "iGoal Football - Italian",
  "iGoal Football - Spanish",
  "Keno",
  "Keno Dashing Derby",
  "Keno Fast League Football",
  "Keno Fast League Football League Match",
  "Keno Fast League Football League Round",
  "Keno Pre-Rec Horses",
  "Kiron Lite",
  "Latam Cup league",
  "Latam Cup single game",
  "Legends Shootout",
  "LinkToWin - Lazo",
  "LinkToWin - Linka Racing",
  "Lotto",
  "Lucky Cars",
  "Lucky Horses",
  "Lucky Loot",
  "Mobile Lite",
  "Mobile Lite - Crash Game",
  "Mobile Lite - Lobby",
  "Mobile Lite - Pick A Box",
  "Mobile Lite - Virtual Champions",
  "Mobile Lite - Virtual Jackpot",
  "Mobile Lite - Virtual League",
  "Mobile Lite - Virtual World Cup",
  "Motor Racing",
  "NHL",
  "Onlyplay",
  "OnlyPlay - Fighter",
  "OnlyPlay – Fighter Jet",
  "Platinum Hounds",
  "Playson",
  "Playson - Book Of Gold Double Chance",
  "Playson - Book Of Gold Multi Chance",
  "Playson - Buffalo Power Hold and Win",
  "Playson - Burning Wins Classic 5 Lines",
  "Playson - Burning Wins x2",
  "Playson - Diamond Fortunator Hold and Win",
  "Playson - Diamond Wins Hold and Win",
  "Playson - Eagle Power Hold and Win",
  "Playson - Fruits and Jokers 100 Lines",
  "Playson - Fruits and Jokers 20 Lines",
  "Playson - Hot Coins Hold and Win",
  "Playson - Imperial Fruits 5 Lines",
  "Playson - Jokers Coins Hold and Win",
  "Playson - Legend of Cleopatra Megaways",
  "Playson - Royal Coins Hold and Win",
  "Playson - Seven and Fruits",
  "Playson - Seven and Fruits 20 Lines",
  "Playson - Slots",
  "Playson - Solar Queen",
  "Playson - Solar Temple",
  "Playson - Sunny Fruits Hold and Win",
  "Playson - Wolf Power Hold and Win",
  "Pre Rec Real Horses",
  "Pre-Rec Greyhound",
  "Pre-Rec Horse Racing Roulette V2",
  "Pre-Rec Horses",
  "Pre-Rec Real Dogs",
  "Pre-Rec Real Dogs (Live Dog Racing)",
  "Pre-Rec Single Seater Motor Racing",
  "Race Clubs",
  "Raceday Tournaments",
  "Rodeo",
  "Single Seater Motor Racing",
  "Slot Car Racing",
  "Soccer Stars",
  "Soccerbet",
  "SoccerBet Football - English",
  "SoccerBet Football - Italian",
  "SoccerBet Football - Turkish",
  "SoccerBet Football League Match - English",
  "SoccerBet Football League Match - Italian",
  "SoccerBet Football League Match - Turkish",
  "SoccerBet Football League Round - Brazil",
  "SoccerBet Football League Round - English",
  "SoccerBet Football League Round - Italian",
  "SoccerBet Football League Round - Turkish",
  "SoccerBet League",
  "SoccerBet Single",
  "SoccerStars - Italy Serie B",
  "SoccerStars - Italy Serie C",
  "SoccerStars Bulgaria",
  "SoccerStars Football - English",
  "SoccerStars Football League Match - English",
  "SoccerStars Football League Round - English",
  "Speed Skating",
  "Spin And Win",
  "Stake logic",
  "StakeLogic - Extreme",
  "StakeLogic - LC2200",
  "StakeLogic - LC3104",
  "StakeLogic - LCEAR",
  "StakeLogic 3200",
  "StakeLogic Live Dealer",
  "StakeLogic Slots",
  "Steeple Chase",
  "Super Over Cricket",
  "Table Tennis",
  "UK Numbers",
  "UK39",
  "UK49",
  "Unikrn",
  "Unikrn - Basketball (NBA2K)",
  "Unikrn - Counter Strike (CSGO)",
  "VSOFT Football",
  "VSOFT Football League Match",
  "VSOFT Football League Week",
  "World Cup",
  "World Ice Hockey League",
  "Africa Cup - Kiron Lite"
];
